// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: graph_cache.proto
// Protobuf C++ Version: 6.33.1

#include "graph_cache.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace lisboa {

inline constexpr LatLon::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        lat_{::int64_t{0}},
        lon_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR LatLon::LatLon(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(LatLon_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct LatLonDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LatLonDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LatLonDefaultTypeInternal() {}
  union {
    LatLon _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LatLonDefaultTypeInternal _LatLon_default_instance_;

inline constexpr Edge::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        type_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR Edge::Edge(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Edge_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct EdgeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EdgeDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EdgeDefaultTypeInternal() {}
  union {
    Edge _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EdgeDefaultTypeInternal _Edge_default_instance_;

inline constexpr Node::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        coords_{nullptr},
        id_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR Node::Node(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Node_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct NodeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NodeDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NodeDefaultTypeInternal() {}
  union {
    Node _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NodeDefaultTypeInternal _Node_default_instance_;

inline constexpr EdgeList::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        edges_{} {}

template <typename>
PROTOBUF_CONSTEXPR EdgeList::EdgeList(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(EdgeList_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct EdgeListDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EdgeListDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EdgeListDefaultTypeInternal() {}
  union {
    EdgeList _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EdgeListDefaultTypeInternal _EdgeList_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR CachedGraph_NodesEntry_DoNotUse::CachedGraph_NodesEntry_DoNotUse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : CachedGraph_NodesEntry_DoNotUse::MapEntry(CachedGraph_NodesEntry_DoNotUse_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : CachedGraph_NodesEntry_DoNotUse::MapEntry() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct CachedGraph_NodesEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CachedGraph_NodesEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CachedGraph_NodesEntry_DoNotUseDefaultTypeInternal() {}
  union {
    CachedGraph_NodesEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CachedGraph_NodesEntry_DoNotUseDefaultTypeInternal _CachedGraph_NodesEntry_DoNotUse_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR CachedGraph_AdjacencyListEntry_DoNotUse::CachedGraph_AdjacencyListEntry_DoNotUse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : CachedGraph_AdjacencyListEntry_DoNotUse::MapEntry(CachedGraph_AdjacencyListEntry_DoNotUse_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : CachedGraph_AdjacencyListEntry_DoNotUse::MapEntry() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct CachedGraph_AdjacencyListEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CachedGraph_AdjacencyListEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CachedGraph_AdjacencyListEntry_DoNotUseDefaultTypeInternal() {}
  union {
    CachedGraph_AdjacencyListEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CachedGraph_AdjacencyListEntry_DoNotUseDefaultTypeInternal _CachedGraph_AdjacencyListEntry_DoNotUse_default_instance_;

inline constexpr CachedGraph::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        nodes_{},
        adjacency_list_{} {}

template <typename>
PROTOBUF_CONSTEXPR CachedGraph::CachedGraph(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CachedGraph_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CachedGraphDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CachedGraphDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CachedGraphDefaultTypeInternal() {}
  union {
    CachedGraph _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CachedGraphDefaultTypeInternal _CachedGraph_default_instance_;
}  // namespace lisboa
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_graph_5fcache_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_graph_5fcache_2eproto = nullptr;
const ::uint32_t
    TableStruct_graph_5fcache_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::lisboa::LatLon, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::lisboa::LatLon, _impl_.lat_),
        PROTOBUF_FIELD_OFFSET(::lisboa::LatLon, _impl_.lon_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::lisboa::Node, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::lisboa::Node, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::lisboa::Node, _impl_.coords_),
        1,
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::lisboa::Edge, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::lisboa::Edge, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::lisboa::Edge, _impl_.type_),
        1,
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::lisboa::EdgeList, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::lisboa::EdgeList, _impl_.edges_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::lisboa::CachedGraph_NodesEntry_DoNotUse, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::lisboa::CachedGraph_NodesEntry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::lisboa::CachedGraph_NodesEntry_DoNotUse, _impl_.value_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::lisboa::CachedGraph_AdjacencyListEntry_DoNotUse, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::lisboa::CachedGraph_AdjacencyListEntry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::lisboa::CachedGraph_AdjacencyListEntry_DoNotUse, _impl_.value_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::lisboa::CachedGraph, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::lisboa::CachedGraph, _impl_.nodes_),
        PROTOBUF_FIELD_OFFSET(::lisboa::CachedGraph, _impl_.adjacency_list_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::lisboa::LatLon)},
        {7, sizeof(::lisboa::Node)},
        {14, sizeof(::lisboa::Edge)},
        {21, sizeof(::lisboa::EdgeList)},
        {26, sizeof(::lisboa::CachedGraph_NodesEntry_DoNotUse)},
        {33, sizeof(::lisboa::CachedGraph_AdjacencyListEntry_DoNotUse)},
        {40, sizeof(::lisboa::CachedGraph)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::lisboa::_LatLon_default_instance_._instance,
    &::lisboa::_Node_default_instance_._instance,
    &::lisboa::_Edge_default_instance_._instance,
    &::lisboa::_EdgeList_default_instance_._instance,
    &::lisboa::_CachedGraph_NodesEntry_DoNotUse_default_instance_._instance,
    &::lisboa::_CachedGraph_AdjacencyListEntry_DoNotUse_default_instance_._instance,
    &::lisboa::_CachedGraph_default_instance_._instance,
};
const char descriptor_table_protodef_graph_5fcache_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\021graph_cache.proto\022\006lisboa\"\"\n\006LatLon\022\013\n"
    "\003lat\030\001 \001(\003\022\013\n\003lon\030\002 \001(\003\"2\n\004Node\022\n\n\002id\030\001 "
    "\001(\003\022\036\n\006coords\030\002 \001(\0132\016.lisboa.LatLon\" \n\004E"
    "dge\022\n\n\002id\030\001 \001(\003\022\014\n\004type\030\002 \001(\t\"\'\n\010EdgeLis"
    "t\022\033\n\005edges\030\001 \003(\0132\014.lisboa.Edge\"\200\002\n\013Cache"
    "dGraph\022-\n\005nodes\030\001 \003(\0132\036.lisboa.CachedGra"
    "ph.NodesEntry\022>\n\016adjacency_list\030\002 \003(\0132&."
    "lisboa.CachedGraph.AdjacencyListEntry\032:\n"
    "\nNodesEntry\022\013\n\003key\030\001 \001(\003\022\033\n\005value\030\002 \001(\0132"
    "\014.lisboa.Node:\0028\001\032F\n\022AdjacencyListEntry\022"
    "\013\n\003key\030\001 \001(\003\022\037\n\005value\030\002 \001(\0132\020.lisboa.Edg"
    "eList:\0028\001b\006proto3"
};
static ::absl::once_flag descriptor_table_graph_5fcache_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_graph_5fcache_2eproto = {
    false,
    false,
    457,
    descriptor_table_protodef_graph_5fcache_2eproto,
    "graph_cache.proto",
    &descriptor_table_graph_5fcache_2eproto_once,
    nullptr,
    0,
    7,
    schemas,
    file_default_instances,
    TableStruct_graph_5fcache_2eproto::offsets,
    file_level_enum_descriptors_graph_5fcache_2eproto,
    file_level_service_descriptors_graph_5fcache_2eproto,
};
namespace lisboa {
// ===================================================================

class LatLon::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<LatLon>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(LatLon, _impl_._has_bits_);
};

LatLon::LatLon(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, LatLon_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:lisboa.LatLon)
}
LatLon::LatLon(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const LatLon& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, LatLon_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE LatLon::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void LatLon::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, lat_),
           0,
           offsetof(Impl_, lon_) -
               offsetof(Impl_, lat_) +
               sizeof(Impl_::lon_));
}
LatLon::~LatLon() {
  // @@protoc_insertion_point(destructor:lisboa.LatLon)
  SharedDtor(*this);
}
inline void LatLon::SharedDtor(MessageLite& self) {
  LatLon& this_ = static_cast<LatLon&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL LatLon::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) LatLon(arena);
}
constexpr auto LatLon::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(LatLon),
                                            alignof(LatLon));
}
constexpr auto LatLon::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_LatLon_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &LatLon::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<LatLon>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &LatLon::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<LatLon>(), &LatLon::ByteSizeLong,
              &LatLon::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(LatLon, _impl_._cached_size_),
          false,
      },
      &LatLon::kDescriptorMethods,
      &descriptor_table_graph_5fcache_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull LatLon_class_data_ =
        LatLon::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
LatLon::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&LatLon_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(LatLon_class_data_.tc_table);
  return LatLon_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
LatLon::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(LatLon, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    LatLon_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::lisboa::LatLon>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int64 lon = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(LatLon, _impl_.lon_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(LatLon, _impl_.lon_)}},
    // int64 lat = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(LatLon, _impl_.lat_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(LatLon, _impl_.lat_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 lat = 1;
    {PROTOBUF_FIELD_OFFSET(LatLon, _impl_.lat_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // int64 lon = 2;
    {PROTOBUF_FIELD_OFFSET(LatLon, _impl_.lon_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void LatLon::Clear() {
// @@protoc_insertion_point(message_clear_start:lisboa.LatLon)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    ::memset(&_impl_.lat_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.lon_) -
        reinterpret_cast<char*>(&_impl_.lat_)) + sizeof(_impl_.lon_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL LatLon::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const LatLon& this_ = static_cast<const LatLon&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL LatLon::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const LatLon& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:lisboa.LatLon)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int64 lat = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_lat() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<1>(
              stream, this_._internal_lat(), target);
    }
  }

  // int64 lon = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_lon() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<2>(
              stream, this_._internal_lon(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:lisboa.LatLon)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t LatLon::ByteSizeLong(const MessageLite& base) {
  const LatLon& this_ = static_cast<const LatLon&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t LatLon::ByteSizeLong() const {
  const LatLon& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:lisboa.LatLon)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // int64 lat = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_lat() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_lat());
      }
    }
    // int64 lon = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_lon() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_lon());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void LatLon::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<LatLon*>(&to_msg);
  auto& from = static_cast<const LatLon&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:lisboa.LatLon)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (from._internal_lat() != 0) {
        _this->_impl_.lat_ = from._impl_.lat_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_lon() != 0) {
        _this->_impl_.lon_ = from._impl_.lon_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void LatLon::CopyFrom(const LatLon& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:lisboa.LatLon)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void LatLon::InternalSwap(LatLon* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(LatLon, _impl_.lon_)
      + sizeof(LatLon::_impl_.lon_)
      - PROTOBUF_FIELD_OFFSET(LatLon, _impl_.lat_)>(
          reinterpret_cast<char*>(&_impl_.lat_),
          reinterpret_cast<char*>(&other->_impl_.lat_));
}

::google::protobuf::Metadata LatLon::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Node::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Node>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Node, _impl_._has_bits_);
};

Node::Node(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Node_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:lisboa.Node)
}
PROTOBUF_NDEBUG_INLINE Node::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::lisboa::Node& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

Node::Node(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Node& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Node_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Node* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.coords_ = (CheckHasBit(cached_has_bits, 0x00000001U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.coords_)
                : nullptr;
  _impl_.id_ = from._impl_.id_;

  // @@protoc_insertion_point(copy_constructor:lisboa.Node)
}
PROTOBUF_NDEBUG_INLINE Node::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void Node::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, coords_),
           0,
           offsetof(Impl_, id_) -
               offsetof(Impl_, coords_) +
               sizeof(Impl_::id_));
}
Node::~Node() {
  // @@protoc_insertion_point(destructor:lisboa.Node)
  SharedDtor(*this);
}
inline void Node::SharedDtor(MessageLite& self) {
  Node& this_ = static_cast<Node&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.coords_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Node::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Node(arena);
}
constexpr auto Node::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Node),
                                            alignof(Node));
}
constexpr auto Node::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Node_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Node::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Node>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Node::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Node>(), &Node::ByteSizeLong,
              &Node::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Node, _impl_._cached_size_),
          false,
      },
      &Node::kDescriptorMethods,
      &descriptor_table_graph_5fcache_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Node_class_data_ =
        Node::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Node::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Node_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Node_class_data_.tc_table);
  return Node_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2>
Node::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Node, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    Node_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::lisboa::Node>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .lisboa.LatLon coords = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(Node, _impl_.coords_)}},
    // int64 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(Node, _impl_.id_), 1>(),
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(Node, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 id = 1;
    {PROTOBUF_FIELD_OFFSET(Node, _impl_.id_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // .lisboa.LatLon coords = 2;
    {PROTOBUF_FIELD_OFFSET(Node, _impl_.coords_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::lisboa::LatLon>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void Node::Clear() {
// @@protoc_insertion_point(message_clear_start:lisboa.Node)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    ABSL_DCHECK(_impl_.coords_ != nullptr);
    _impl_.coords_->Clear();
  }
  _impl_.id_ = ::int64_t{0};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Node::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Node& this_ = static_cast<const Node&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Node::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Node& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:lisboa.Node)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int64 id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<1>(
              stream, this_._internal_id(), target);
    }
  }

  // .lisboa.LatLon coords = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.coords_, this_._impl_.coords_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:lisboa.Node)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Node::ByteSizeLong(const MessageLite& base) {
  const Node& this_ = static_cast<const Node&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Node::ByteSizeLong() const {
  const Node& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:lisboa.Node)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // .lisboa.LatLon coords = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.coords_);
    }
    // int64 id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_id());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Node::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Node*>(&to_msg);
  auto& from = static_cast<const Node&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:lisboa.Node)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      ABSL_DCHECK(from._impl_.coords_ != nullptr);
      if (_this->_impl_.coords_ == nullptr) {
        _this->_impl_.coords_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.coords_);
      } else {
        _this->_impl_.coords_->MergeFrom(*from._impl_.coords_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_id() != 0) {
        _this->_impl_.id_ = from._impl_.id_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Node::CopyFrom(const Node& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:lisboa.Node)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Node::InternalSwap(Node* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Node, _impl_.id_)
      + sizeof(Node::_impl_.id_)
      - PROTOBUF_FIELD_OFFSET(Node, _impl_.coords_)>(
          reinterpret_cast<char*>(&_impl_.coords_),
          reinterpret_cast<char*>(&other->_impl_.coords_));
}

::google::protobuf::Metadata Node::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Edge::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Edge>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Edge, _impl_._has_bits_);
};

Edge::Edge(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Edge_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:lisboa.Edge)
}
PROTOBUF_NDEBUG_INLINE Edge::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::lisboa::Edge& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        type_(arena, from.type_) {}

Edge::Edge(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Edge& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Edge_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Edge* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.id_ = from._impl_.id_;

  // @@protoc_insertion_point(copy_constructor:lisboa.Edge)
}
PROTOBUF_NDEBUG_INLINE Edge::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        type_(arena) {}

inline void Edge::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.id_ = {};
}
Edge::~Edge() {
  // @@protoc_insertion_point(destructor:lisboa.Edge)
  SharedDtor(*this);
}
inline void Edge::SharedDtor(MessageLite& self) {
  Edge& this_ = static_cast<Edge&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.type_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Edge::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Edge(arena);
}
constexpr auto Edge::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Edge),
                                            alignof(Edge));
}
constexpr auto Edge::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Edge_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Edge::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Edge>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Edge::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Edge>(), &Edge::ByteSizeLong,
              &Edge::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Edge, _impl_._cached_size_),
          false,
      },
      &Edge::kDescriptorMethods,
      &descriptor_table_graph_5fcache_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Edge_class_data_ =
        Edge::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Edge::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Edge_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Edge_class_data_.tc_table);
  return Edge_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 24, 2>
Edge::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Edge, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Edge_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::lisboa::Edge>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string type = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(Edge, _impl_.type_)}},
    // int64 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(Edge, _impl_.id_), 1>(),
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(Edge, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 id = 1;
    {PROTOBUF_FIELD_OFFSET(Edge, _impl_.id_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // string type = 2;
    {PROTOBUF_FIELD_OFFSET(Edge, _impl_.type_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\13\0\4\0\0\0\0\0"
    "lisboa.Edge"
    "type"
  }},
};
PROTOBUF_NOINLINE void Edge::Clear() {
// @@protoc_insertion_point(message_clear_start:lisboa.Edge)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.type_.ClearNonDefaultToEmpty();
  }
  _impl_.id_ = ::int64_t{0};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Edge::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Edge& this_ = static_cast<const Edge&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Edge::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Edge& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:lisboa.Edge)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int64 id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<1>(
              stream, this_._internal_id(), target);
    }
  }

  // string type = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_type().empty()) {
      const ::std::string& _s = this_._internal_type();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "lisboa.Edge.type");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:lisboa.Edge)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Edge::ByteSizeLong(const MessageLite& base) {
  const Edge& this_ = static_cast<const Edge&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Edge::ByteSizeLong() const {
  const Edge& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:lisboa.Edge)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // string type = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_type().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_type());
      }
    }
    // int64 id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_id());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Edge::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Edge*>(&to_msg);
  auto& from = static_cast<const Edge&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:lisboa.Edge)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_type().empty()) {
        _this->_internal_set_type(from._internal_type());
      } else {
        if (_this->_impl_.type_.IsDefault()) {
          _this->_internal_set_type("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_id() != 0) {
        _this->_impl_.id_ = from._impl_.id_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Edge::CopyFrom(const Edge& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:lisboa.Edge)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Edge::InternalSwap(Edge* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.type_, &other->_impl_.type_, arena);
  swap(_impl_.id_, other->_impl_.id_);
}

::google::protobuf::Metadata Edge::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class EdgeList::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<EdgeList>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(EdgeList, _impl_._has_bits_);
};

EdgeList::EdgeList(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, EdgeList_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:lisboa.EdgeList)
}
PROTOBUF_NDEBUG_INLINE EdgeList::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::lisboa::EdgeList& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        edges_{visibility, arena, from.edges_} {}

EdgeList::EdgeList(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const EdgeList& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, EdgeList_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  EdgeList* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:lisboa.EdgeList)
}
PROTOBUF_NDEBUG_INLINE EdgeList::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        edges_{visibility, arena} {}

inline void EdgeList::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
EdgeList::~EdgeList() {
  // @@protoc_insertion_point(destructor:lisboa.EdgeList)
  SharedDtor(*this);
}
inline void EdgeList::SharedDtor(MessageLite& self) {
  EdgeList& this_ = static_cast<EdgeList&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL EdgeList::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) EdgeList(arena);
}
constexpr auto EdgeList::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(EdgeList, _impl_.edges_) +
          decltype(EdgeList::_impl_.edges_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(EdgeList), alignof(EdgeList), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&EdgeList::PlacementNew_,
                                 sizeof(EdgeList),
                                 alignof(EdgeList));
  }
}
constexpr auto EdgeList::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_EdgeList_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &EdgeList::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<EdgeList>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &EdgeList::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<EdgeList>(), &EdgeList::ByteSizeLong,
              &EdgeList::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(EdgeList, _impl_._cached_size_),
          false,
      },
      &EdgeList::kDescriptorMethods,
      &descriptor_table_graph_5fcache_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull EdgeList_class_data_ =
        EdgeList::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
EdgeList::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&EdgeList_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(EdgeList_class_data_.tc_table);
  return EdgeList_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
EdgeList::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(EdgeList, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    EdgeList_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::lisboa::EdgeList>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .lisboa.Edge edges = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(EdgeList, _impl_.edges_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .lisboa.Edge edges = 1;
    {PROTOBUF_FIELD_OFFSET(EdgeList, _impl_.edges_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::lisboa::Edge>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void EdgeList::Clear() {
// @@protoc_insertion_point(message_clear_start:lisboa.EdgeList)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _impl_.edges_.Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL EdgeList::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const EdgeList& this_ = static_cast<const EdgeList&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL EdgeList::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const EdgeList& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:lisboa.EdgeList)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated .lisboa.Edge edges = 1;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_edges_size());
         i < n; i++) {
      const auto& repfield = this_._internal_edges().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              1, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:lisboa.EdgeList)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t EdgeList::ByteSizeLong(const MessageLite& base) {
  const EdgeList& this_ = static_cast<const EdgeList&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t EdgeList::ByteSizeLong() const {
  const EdgeList& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:lisboa.EdgeList)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .lisboa.Edge edges = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_edges_size();
      for (const auto& msg : this_._internal_edges()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void EdgeList::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<EdgeList*>(&to_msg);
  auto& from = static_cast<const EdgeList&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:lisboa.EdgeList)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _this->_internal_mutable_edges()->InternalMergeFromWithArena(
        ::google::protobuf::MessageLite::internal_visibility(), arena,
        from._internal_edges());
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void EdgeList::CopyFrom(const EdgeList& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:lisboa.EdgeList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void EdgeList::InternalSwap(EdgeList* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.edges_.InternalSwap(&other->_impl_.edges_);
}

::google::protobuf::Metadata EdgeList::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
CachedGraph_NodesEntry_DoNotUse::CachedGraph_NodesEntry_DoNotUse()
    : SuperType(CachedGraph_NodesEntry_DoNotUse_class_data_.base()) {}
CachedGraph_NodesEntry_DoNotUse::CachedGraph_NodesEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
    : SuperType(arena, CachedGraph_NodesEntry_DoNotUse_class_data_.base()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
CachedGraph_NodesEntry_DoNotUse::CachedGraph_NodesEntry_DoNotUse() : SuperType() {}
CachedGraph_NodesEntry_DoNotUse::CachedGraph_NodesEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
inline void* PROTOBUF_NONNULL CachedGraph_NodesEntry_DoNotUse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CachedGraph_NodesEntry_DoNotUse(arena);
}
constexpr auto CachedGraph_NodesEntry_DoNotUse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(CachedGraph_NodesEntry_DoNotUse),
                                            alignof(CachedGraph_NodesEntry_DoNotUse));
}
constexpr auto CachedGraph_NodesEntry_DoNotUse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CachedGraph_NodesEntry_DoNotUse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CachedGraph_NodesEntry_DoNotUse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CachedGraph_NodesEntry_DoNotUse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CachedGraph_NodesEntry_DoNotUse::SharedDtor,
          static_cast<void (::google::protobuf::MessageLite::*)()>(&CachedGraph_NodesEntry_DoNotUse::ClearImpl),
              ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
              ,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CachedGraph_NodesEntry_DoNotUse, _impl_._cached_size_),
          false,
      },
      &CachedGraph_NodesEntry_DoNotUse::kDescriptorMethods,
      &descriptor_table_graph_5fcache_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CachedGraph_NodesEntry_DoNotUse_class_data_ =
        CachedGraph_NodesEntry_DoNotUse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CachedGraph_NodesEntry_DoNotUse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CachedGraph_NodesEntry_DoNotUse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CachedGraph_NodesEntry_DoNotUse_class_data_.tc_table);
  return CachedGraph_NodesEntry_DoNotUse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2>
CachedGraph_NodesEntry_DoNotUse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CachedGraph_NodesEntry_DoNotUse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    CachedGraph_NodesEntry_DoNotUse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::lisboa::CachedGraph_NodesEntry_DoNotUse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .lisboa.Node value = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(CachedGraph_NodesEntry_DoNotUse, _impl_.value_)}},
    // int64 key = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CachedGraph_NodesEntry_DoNotUse, _impl_.key_), 1>(),
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(CachedGraph_NodesEntry_DoNotUse, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 key = 1;
    {PROTOBUF_FIELD_OFFSET(CachedGraph_NodesEntry_DoNotUse, _impl_.key_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // .lisboa.Node value = 2;
    {PROTOBUF_FIELD_OFFSET(CachedGraph_NodesEntry_DoNotUse, _impl_.value_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::lisboa::Node>()},
  }},
  {{
  }},
};
// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
CachedGraph_AdjacencyListEntry_DoNotUse::CachedGraph_AdjacencyListEntry_DoNotUse()
    : SuperType(CachedGraph_AdjacencyListEntry_DoNotUse_class_data_.base()) {}
CachedGraph_AdjacencyListEntry_DoNotUse::CachedGraph_AdjacencyListEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
    : SuperType(arena, CachedGraph_AdjacencyListEntry_DoNotUse_class_data_.base()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
CachedGraph_AdjacencyListEntry_DoNotUse::CachedGraph_AdjacencyListEntry_DoNotUse() : SuperType() {}
CachedGraph_AdjacencyListEntry_DoNotUse::CachedGraph_AdjacencyListEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
inline void* PROTOBUF_NONNULL CachedGraph_AdjacencyListEntry_DoNotUse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CachedGraph_AdjacencyListEntry_DoNotUse(arena);
}
constexpr auto CachedGraph_AdjacencyListEntry_DoNotUse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(CachedGraph_AdjacencyListEntry_DoNotUse),
                                            alignof(CachedGraph_AdjacencyListEntry_DoNotUse));
}
constexpr auto CachedGraph_AdjacencyListEntry_DoNotUse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CachedGraph_AdjacencyListEntry_DoNotUse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CachedGraph_AdjacencyListEntry_DoNotUse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CachedGraph_AdjacencyListEntry_DoNotUse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CachedGraph_AdjacencyListEntry_DoNotUse::SharedDtor,
          static_cast<void (::google::protobuf::MessageLite::*)()>(&CachedGraph_AdjacencyListEntry_DoNotUse::ClearImpl),
              ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
              ,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CachedGraph_AdjacencyListEntry_DoNotUse, _impl_._cached_size_),
          false,
      },
      &CachedGraph_AdjacencyListEntry_DoNotUse::kDescriptorMethods,
      &descriptor_table_graph_5fcache_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CachedGraph_AdjacencyListEntry_DoNotUse_class_data_ =
        CachedGraph_AdjacencyListEntry_DoNotUse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CachedGraph_AdjacencyListEntry_DoNotUse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CachedGraph_AdjacencyListEntry_DoNotUse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CachedGraph_AdjacencyListEntry_DoNotUse_class_data_.tc_table);
  return CachedGraph_AdjacencyListEntry_DoNotUse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2>
CachedGraph_AdjacencyListEntry_DoNotUse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CachedGraph_AdjacencyListEntry_DoNotUse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    CachedGraph_AdjacencyListEntry_DoNotUse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::lisboa::CachedGraph_AdjacencyListEntry_DoNotUse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .lisboa.EdgeList value = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(CachedGraph_AdjacencyListEntry_DoNotUse, _impl_.value_)}},
    // int64 key = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CachedGraph_AdjacencyListEntry_DoNotUse, _impl_.key_), 1>(),
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(CachedGraph_AdjacencyListEntry_DoNotUse, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 key = 1;
    {PROTOBUF_FIELD_OFFSET(CachedGraph_AdjacencyListEntry_DoNotUse, _impl_.key_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // .lisboa.EdgeList value = 2;
    {PROTOBUF_FIELD_OFFSET(CachedGraph_AdjacencyListEntry_DoNotUse, _impl_.value_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::lisboa::EdgeList>()},
  }},
  {{
  }},
};
// ===================================================================

class CachedGraph::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CachedGraph>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CachedGraph, _impl_._has_bits_);
};

CachedGraph::CachedGraph(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CachedGraph_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:lisboa.CachedGraph)
}
PROTOBUF_NDEBUG_INLINE CachedGraph::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::lisboa::CachedGraph& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        nodes_{visibility, arena, from.nodes_},
        adjacency_list_{visibility, arena, from.adjacency_list_} {}

CachedGraph::CachedGraph(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CachedGraph& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CachedGraph_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CachedGraph* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:lisboa.CachedGraph)
}
PROTOBUF_NDEBUG_INLINE CachedGraph::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        nodes_{visibility, arena},
        adjacency_list_{visibility, arena} {}

inline void CachedGraph::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
CachedGraph::~CachedGraph() {
  // @@protoc_insertion_point(destructor:lisboa.CachedGraph)
  SharedDtor(*this);
}
inline void CachedGraph::SharedDtor(MessageLite& self) {
  CachedGraph& this_ = static_cast<CachedGraph&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CachedGraph::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CachedGraph(arena);
}
constexpr auto CachedGraph::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(CachedGraph, _impl_.nodes_) +
          decltype(CachedGraph::_impl_.nodes_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(CachedGraph, _impl_.adjacency_list_) +
          decltype(CachedGraph::_impl_.adjacency_list_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(CachedGraph), alignof(CachedGraph), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&CachedGraph::PlacementNew_,
                                 sizeof(CachedGraph),
                                 alignof(CachedGraph));
  }
}
constexpr auto CachedGraph::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CachedGraph_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CachedGraph::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CachedGraph>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CachedGraph::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CachedGraph>(), &CachedGraph::ByteSizeLong,
              &CachedGraph::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CachedGraph, _impl_._cached_size_),
          false,
      },
      &CachedGraph::kDescriptorMethods,
      &descriptor_table_graph_5fcache_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CachedGraph_class_data_ =
        CachedGraph::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CachedGraph::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CachedGraph_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CachedGraph_class_data_.tc_table);
  return CachedGraph_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 2, 4, 0, 2>
CachedGraph::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CachedGraph, _impl_._has_bits_),
    0, // no _extensions_
    2, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    4,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    CachedGraph_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::lisboa::CachedGraph>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // map<int64, .lisboa.Node> nodes = 1;
    {PROTOBUF_FIELD_OFFSET(CachedGraph, _impl_.nodes_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
    // map<int64, .lisboa.EdgeList> adjacency_list = 2;
    {PROTOBUF_FIELD_OFFSET(CachedGraph, _impl_.adjacency_list_), _Internal::kHasBitsOffset + 1, 2, (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
  }},
  {{
      {::_pbi::TcParser::GetMapAuxInfo(
          0, 0, 3, 11, 0)},
      {::_pbi::TcParser::GetTable<::lisboa::Node>()},
      {::_pbi::TcParser::GetMapAuxInfo(
          0, 0, 3, 11, 0)},
      {::_pbi::TcParser::GetTable<::lisboa::EdgeList>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void CachedGraph::Clear() {
// @@protoc_insertion_point(message_clear_start:lisboa.CachedGraph)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _impl_.nodes_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _impl_.adjacency_list_.Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CachedGraph::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CachedGraph& this_ = static_cast<const CachedGraph&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CachedGraph::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CachedGraph& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:lisboa.CachedGraph)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // map<int64, .lisboa.Node> nodes = 1;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_nodes().empty()) {
      using MapType = ::google::protobuf::Map<::int64_t, ::lisboa::Node>;
      using WireHelper = _pbi::MapEntryFuncs<::int64_t, ::lisboa::Node,
                                     _pbi::WireFormatLite::TYPE_INT64,
                                     _pbi::WireFormatLite::TYPE_MESSAGE>;
      const auto& field = this_._internal_nodes();

      if (stream->IsSerializationDeterministic() && field.size() > 1) {
        for (const auto& entry : ::google::protobuf::internal::MapSorterFlat<MapType>(field)) {
          target = WireHelper::InternalSerialize(
              1, entry.first, entry.second, target, stream);
        }
      } else {
        for (const auto& entry : field) {
          target = WireHelper::InternalSerialize(
              1, entry.first, entry.second, target, stream);
        }
      }
    }
  }

  // map<int64, .lisboa.EdgeList> adjacency_list = 2;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_adjacency_list().empty()) {
      using MapType = ::google::protobuf::Map<::int64_t, ::lisboa::EdgeList>;
      using WireHelper = _pbi::MapEntryFuncs<::int64_t, ::lisboa::EdgeList,
                                     _pbi::WireFormatLite::TYPE_INT64,
                                     _pbi::WireFormatLite::TYPE_MESSAGE>;
      const auto& field = this_._internal_adjacency_list();

      if (stream->IsSerializationDeterministic() && field.size() > 1) {
        for (const auto& entry : ::google::protobuf::internal::MapSorterFlat<MapType>(field)) {
          target = WireHelper::InternalSerialize(
              2, entry.first, entry.second, target, stream);
        }
      } else {
        for (const auto& entry : field) {
          target = WireHelper::InternalSerialize(
              2, entry.first, entry.second, target, stream);
        }
      }
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:lisboa.CachedGraph)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CachedGraph::ByteSizeLong(const MessageLite& base) {
  const CachedGraph& this_ = static_cast<const CachedGraph&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CachedGraph::ByteSizeLong() const {
  const CachedGraph& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:lisboa.CachedGraph)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // map<int64, .lisboa.Node> nodes = 1;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_nodes_size());
      for (const auto& entry : this_._internal_nodes()) {
        total_size += _pbi::MapEntryFuncs<::int64_t, ::lisboa::Node,
                                       _pbi::WireFormatLite::TYPE_INT64,
                                       _pbi::WireFormatLite::TYPE_MESSAGE>::ByteSizeLong(entry.first, entry.second);
      }
    }
    // map<int64, .lisboa.EdgeList> adjacency_list = 2;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_adjacency_list_size());
      for (const auto& entry : this_._internal_adjacency_list()) {
        total_size += _pbi::MapEntryFuncs<::int64_t, ::lisboa::EdgeList,
                                       _pbi::WireFormatLite::TYPE_INT64,
                                       _pbi::WireFormatLite::TYPE_MESSAGE>::ByteSizeLong(entry.first, entry.second);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CachedGraph::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<CachedGraph*>(&to_msg);
  auto& from = static_cast<const CachedGraph&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:lisboa.CachedGraph)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_impl_.nodes_.MergeFrom(from._impl_.nodes_);
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _this->_impl_.adjacency_list_.MergeFrom(from._impl_.adjacency_list_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void CachedGraph::CopyFrom(const CachedGraph& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:lisboa.CachedGraph)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CachedGraph::InternalSwap(CachedGraph* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.nodes_.InternalSwap(&other->_impl_.nodes_);
  _impl_.adjacency_list_.InternalSwap(&other->_impl_.adjacency_list_);
}

::google::protobuf::Metadata CachedGraph::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace lisboa
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_graph_5fcache_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
